name: pipenv-update
on:
  schedule:
    - cron:  '8 22 * * 1'
  workflow_dispatch:

permissions: read-all

jobs:
  pipenv-update:
    runs-on: [self-hosted, public, linux, x64]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT_SECRET }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4  # v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984  # v4
        with:
          python-version: 3.7
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pipenv update
          git add -u
          git commit -m "update pipenv packages"
        env:
          GITHUB_TOKEN: ${{ github.PAT_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@6d6857d36972b65feb161a90e484f2984215f83e  # v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: '[AUTO-PR] Update pipenv packages'
          body: |
            bump pipenv packages
            - Auto-generated by [pipenv-update github action](https://github.com/bridgecrewio/checkov/blob/master/.github/workflows/pipenv-update.yml)
          labels: automated pr
          branch: pipenvfix
          branch-suffix: timestamp
