name: PR Test

on: pull_request

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
        with:
          python-version: 3.9
      - name: pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3

  cfn-lint:
    runs-on: [self-hosted, public, linux, x64]
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
        with:
          python-version: 3.7
      - name: Install cfn-lint
        run: |
          pip install -U cfn-lint
      - name: Lint Cloudformation templates
        run: |
          cfn-lint tests/cloudformation/checks/resource/aws/**/* -i W

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
      with:
        python-version: 3.7
    - name: Install pipenv
      run: |
        python -m pip install --no-cache-dir --upgrade pipenv
    - name: Install dependencies
      run: |
        pipenv --python 3.7
        pipenv install --dev
        pipenv run pip install typed-ast  # for some reason this has an old version
    - name: Run Mypy
      run: |
        pipenv run mypy

  unit-tests:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Install dependencies
        run: |
          pipenv --python ${{ matrix.python }}
          pipenv install --dev -v
      - uses: imranismail/setup-kustomize@049197ab4eedae719afdcfa2aa852ae69876d015  # v2
      - name: Unit tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pipenv run python -m pytest tests

  integration-tests:
    strategy:
      fail-fast: true
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a  # v3
      - uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82  # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: imranismail/setup-kustomize@049197ab4eedae719afdcfa2aa852ae69876d015  # v2
        if: ${{ runner.os != 'windows' }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Build & install checkov package
        run: |
          pipenv --python ${{ matrix.python }}
          pipenv run pip install pytest pytest-xdist
          pipenv run python setup.py sdist bdist_wheel
          bash -c 'pipenv run pip install dist/checkov-*.whl'
      - name: Clone Terragoat - vulnerable terraform
        run: git clone https://github.com/bridgecrewio/terragoat
      - name: Clone Cfngoat - vulnerable cloudformation
        run: git clone https://github.com/bridgecrewio/cfngoat
      - name: Clone Kubernetes-goat - vulnerable kubernetes
        run: git clone https://github.com/madhuakula/kubernetes-goat
      - name: Clone kustomize-goat - vulnerable kustomize
        run: git clone https://github.com/bridgecrewio/kustomizegoat
      - name: Create checkov reports
        env:
          LOG_LEVEL: INFO
          BC_KEY: ${{ secrets.BC_API_KEY }}
        run: |
          # Just making sure the API key tests don't run on PRs
          bash -c './integration_tests/prepare_data.sh ${{ matrix.os }} 3.8'
      - name: Run integration tests
        run: |
          pipenv run pytest integration_tests -k 'not api_key'

  performance-tests:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    env:
      working-directory: ./performance_tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b  # v3
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v4
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a  # v3
      - uses: azure/setup-helm@f382f75448129b3be48f8121b9857be18d815a82  # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: imranismail/setup-kustomize@049197ab4eedae719afdcfa2aa852ae69876d015  # v2
        if: ${{ runner.os != 'windows' }}
      - name: Install pipenv
        run: |
          python -m pip install --no-cache-dir --upgrade pipenv
      - name: Build & install checkov package
        run: |
          pipenv --python ${{ matrix.python }}
          # 'py' package is used in 'pytest-benchmark', but 'pytest' removed it in their latest version         
          pipenv run pip install pytest pytest-benchmark py
          pipenv run python setup.py sdist bdist_wheel
          bash -c 'pipenv run pip install dist/checkov-*.whl'
      - name: Clone terraform-aws-components
        run: git clone --branch 0.182.0 https://github.com/cloudposse/terraform-aws-components.git
        working-directory: ${{ env.working-directory }}
      - name: Clone aws-cloudformation-templates
        run: git clone --branch 0.0.1 https://github.com/awslabs/aws-cloudformation-templates.git
        working-directory: ${{ env.working-directory }}
      - name: Clone kubernetes-yaml-templates
        run: git clone https://github.com/dennyzhang/kubernetes-yaml-templates.git
        working-directory: ${{ env.working-directory }}
      - name: Run performance tests
        run: |
          pipenv run pytest
        working-directory: ${{ env.working-directory }}
